### PR TITLE
Add support deserializing the bin format family

### PR DESCRIPTION
**Pull request by Sean-Der**
Hey @laruence this is a WIP!
I am going to add tests for deserialization as well.

However, I don't know when we would want to serialize something with this format?

### CODE REVIEW

**Comment by laruence** [comment]
I am not sure about this neither.. maybe we could hold from committing this for now.... :<

**Comment by Sean-Der** [comment]
@laruence anything works for me! I am just trying to close out #36. Are there any issues that you think are important and well defined?

(other [msgpack implementations](https://github.com/reeze/msgpack-hhvm/issues/1) are at the same place as us so it would be nice to give people something to like this)

**Comment by laruence** [comment]
hmm, then okey, commit it.. thanks :)

**Comment by Sean-Der** [comment]
Awesome, thanks @laruence!

Also, do you have issues you would like me to look at in particular? I am going to look at the current test fails, then go through the issues oldest -> newest.

**Comment by laruence** [comment]
Nope, please do whatever you want :), if you needs some discussions, just ping me , thanks

**Pull request closed without merging**
