### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by umbri**
MsgPack support streaming, but no info about this, this can be found only in tests.
For me, this feature was deciding.

### CODE REVIEW

**Comment by dpordomingo** [comment]
Quite useful info!
It'd be great if this PR is merged!
thanks @umbri 
ping @Sean-Der @laruence

**Comment by stamster** [comment]
I don't know why this simple PR isn't accepted, perhaps that the Travis CI failed? Well, it's just .md file.

**Comment by umbri** [comment]
Seems like this project is dead: use https://github.com/rybakit/msgpack.php
@rybakit Thank you

**Comment by umbri** [comment]
Care: https://github.com/msgpack/msgpack-php/issues/105 https://github.com/msgpack/msgpack-php/issues/107

**Comment by stamster** [comment]
@umbri How come it is dead? it is official repo of the msgpack.

**Comment by umbri** [comment]
@stamster This is my opinion, no one comment https://github.com/msgpack/msgpack-php/issues/105 or https://github.com/msgpack/msgpack-php/issues/107, no one merge pull requests, if you check issues there are much of them, so why I am using https://github.com/rybakit/msgpack.php

**Comment by stamster** [comment]
@umbri Yes, that's true. Many projects seems abandoned lately, so devs must be busy banging their company code :1st_place_medal:

**Pull request merged**
