### PR TITLE
What is this the 90's

### PR DESCRIPTION
**Pull request by philsturgeon**
:trollface: 

But really lets update that. Short array syntax was introduced in 5.4, which is no longer supported its so old.

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
You should also remove the versions this breaks from the Travis grid

**Comment by philsturgeon** [comment]
@ciaranmcnulty the break has nothing to do with my change, it's just not working on 5.5 and 5.6.

**Comment by ciaranmcnulty** [comment]
Sure but you know your change will knock out `5.2` and `5.3`

**Comment by philsturgeon** [comment]
My change does not effect anyones code. If they want to try using new syntax on an old version then it’ll fail and they’ll go “oh yeah, I’m still using a decade old version so I should use the right syntax.”

For the 98% of PHP developers not on 5.3, this is fine.

**Comment by ciaranmcnulty** [comment]
Sorry, I blanked on the fact this was in `README.md` not actual code! Carry on.

**Comment by laruence** [comment]
as msgpack is also support php-5.3, and I don't see any gain by changing this... closing this. thanks anyway :)

**Pull request closed without merging**
