### PR TITLE
Use own definition of msgpack_unserialize_data_t

### LINKED ISSUE #100: PHP 7.1 RC1 compile fail.
msgpack-php-master/msgpack.c: In function ‘ps_srlzr_decode_msgpack’:
msgpack-php-master/msgpack.c:160: error: storage size of ‘var_hash’ isn’t known
msgpack-php-master/msgpack.c: In function ‘php_msgpack_unserialize’:
msgpack-php-master/msgpack.c:210: error: storage size of ‘var_hash’ isn’t known
make: **\* [msgpack.lo] Error 1

### PR DESCRIPTION
**Pull request by sodabrew**
PHP changes its struct php_unserialize_data, so we need our own. Closes #100.

### CODE REVIEW

**Comment by sodabrew** [comment]
Test failures on PHP 7.0 (pre-existing, not caused by this PR):
```
TEST 41/122 [tests/041.phpt]
========DIFF========
022+ float(-0)
023+ float(-0)
024+ cb8000000000000000
022- float(0)
023- float(0)
024- cb0000000000000000
========DONE========
FAIL Check for double NaN, Inf, -Inf, 0, and -0 [tests/041.phpt] 
```

Test failures on PHP 7.1 (don't appear to be caused by this PR):
```
TEST 37/122 [tests/040.phpt]
========DIFF========
001+ ec
001- 
002+ int(-20)
========DONE========
FAIL broken random data test [tests/040.phpt] 
TEST 38/122 [tests/040b.phpt]
========DIFF========
001+ ec
001- 
002+ int(-20)
========DONE========
FAIL broken random data test : MessagePack class [tests/040b.phpt] 
TEST 39/122 [tests/040c.phpt]
========DIFF========
001+ ec
001- 
002+ int(-20)
========DONE========
FAIL broken random data test : MessagePackUnpacker::feed [tests/040c.phpt] 
TEST 40/122 [tests/040d.phpt]
========DIFF========
001+ ec
001- 
002+ int(-20)
========DONE========
FAIL broken random data test : MessagePackUnpacker::execute [tests/040d.phpt] 
TEST 41/122 [tests/041.phpt]
========DIFF========
022+ float(-0)
023+ float(-0)
024+ cb8000000000000000
022- float(0)
023- float(0)
024- cb0000000000000000
========DONE========
FAIL Check for double NaN, Inf, -Inf, 0, and -0 [tests/041.phpt] 
```

**Comment by sodabrew** [comment]
@laruence @remicollet This PR based on your suggestion: https://github.com/msgpack/msgpack-php/issues/100#issuecomment-247116715

**Comment by sodabrew** [comment]
Ping @laruence

**Comment by sodabrew** [comment]
Annoying ping for attention because PHP 7.1 is coming soon.

**Comment by ProPheT777** [comment]
Hello, 

We had a similar issue during migrating our container to php 7.1, 

I think it's related : 

```
running: make
/bin/bash /tmp/pear/temp/pear-build-defaultuserJehL4h/msgpack-2.0.1/libtool --mode=compile cc  -I. -I/tmp/pear/temp/msgpack -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserJehL4h/msgpack-2.0.1/include -I/tmp/pear/temp/pear-build-defaultuserJehL4h/msgpack-2.0.1/main -I/tmp/pear/temp/msgpack -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/msgpack/msgpack.c -o msgpack.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/msgpack -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserJehL4h/msgpack-2.0.1/include -I/tmp/pear/temp/pear-build-defaultuserJehL4h/msgpack-2.0.1/main -I/tmp/pear/temp/msgpack -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/msgpack/msgpack.c  -fPIC -DPIC -o .libs/msgpack.o
/tmp/pear/temp/msgpack/msgpack.c: In function 'ps_srlzr_decode_msgpack':
/tmp/pear/temp/msgpack/msgpack.c:160:29: error: storage size of 'var_hash' isn't known
  msgpack_unserialize_data_t var_hash;
                             ^
/tmp/pear/temp/msgpack/msgpack.c: In function 'php_msgpack_unserialize':
/tmp/pear/temp/msgpack/msgpack.c:210:29: error: storage size of 'var_hash' isn't known
  msgpack_unserialize_data_t var_hash;
                             ^
make: *** [msgpack.lo] Error 1
ERROR: `make' failed
```

What is missing for merge and released? Because this issue is a blocker

**Comment by RochesterinNYC** [comment]
The Cloud Foundry Buildpacks team is coming across the issue that this PR resolves as well.

**Comment by sodabrew** [comment]
Annoying ping for attention because PHP 7.1.0 was released yesterday.

**Comment by jchesterpivotal** [comment]
Is there some way that Buildpacks team can help?

**Comment by Sean-Der** [comment]
Merged!

Sorry that this took so long, I am not very active with PHP anymore. I don't have access to release on PECL, but I will get master back in a good state for 7.1

thanks

**Comment by laruence** [comment]
I will make a release when it's done, thanks :)

**Comment by Sean-Der** [comment]
awesome, thank you @laruence !

**Comment by ProPheT777** [comment]
Thank you very much guys!

**Pull request closed without merging**
