### PR TITLE
support str8 type

### PR DESCRIPTION
**Pull request by wudikua**

### CODE REVIEW

**Comment by nizsheanez** [comment]
Helly, guys. Is this repo still alive? Or we must create a fork?

**Comment by laruence** [comment]
it's alive, just because I am busy with lots of other taskes, maybe I need some help...  :<

**Comment by nizsheanez** [comment]
cool, can how can we help with this pull request?

**Comment by laruence** [comment]
make a test script, (phpt), to show the origin problem, and test this behavior(after merge)

**Comment by nizsheanez** [comment]
@laruence, is it enough?

**Comment by laruence** [comment]
@nizsheanez already merged :)

**Comment by nizsheanez** [comment]
@laruence, can we bump new version in PECL?

**Comment by laruence** [comment]
yeah, I will do it later this weekend..

**Comment by nizsheanez** [comment]
wow, nice

**Comment by nizsheanez** [comment]
gentle reminder

**Comment by nizsheanez** [comment]
@laruence, can we bump new version in PECL?

**Comment by laruence** [comment]
sorry for delay, I was out for a conf . anyway, it's done(0.5.6 is released). thanks :)

**Pull request merged**
