### PR TITLE
Travis - added PHP 5.6 for tests

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by jippi** [comment]
:+1:

**Comment by Sean-Der** [comment]
Hey @ovr

Thanks for the PR, I am going to look into those test fails this weekend (I know at least some of them are not new) and then merge this!

**Comment by jippi** [comment]
so there a know php5.6 bugs, or just known rare-case bugs in general?

**Comment by Sean-Der** [comment]
cherry-picked 7b321ea1e7ee144345df6fb3773524024b6dbe0e thank you @ovr !

**Pull request closed without merging**
