### PR TITLE
Add PHP 7.2 to the Travis CI matrix

### PR DESCRIPTION
**Pull request by sodabrew**
This PR will get PHP 7.1 and 7.2 fully tested. Then the PHP 7.3 PR #124 can be a bunch smaller and focus only on the recursion changes there.

### CODE REVIEW

**Comment by sodabrew** [comment]
@laruence @Sean-Der are you available begin a train to get to PHP 7.3? There will be a number of PRs on the way from myself and @remicollet

**Comment by sodabrew** [comment]
Hi! Is anybody available to support getting this module ready for the PHP 7.3 release?

**Comment by Jan-E** [comment]
> Hi! Is anybody available to support getting this module ready for the PHP 7.3 release?

Try @remicollet 
See https://github.com/msgpack/msgpack-php/pull/124

**Comment by andypost** [comment]
FYI on aarch64 one test fails http://build.alpinelinux.org/buildlogs/build-edge-aarch64/community/php7-pecl-msgpack/php7-pecl-msgpack-2.0.3-r1.log
```
FAILED TEST SUMMARY
---------------------------------------------------------------------
Profiling perf test. [tests/035.phpt]
=====================================================================
```

**Comment by ronald2wing** [comment]
@sodabrew Your PR is almost working. Please fix that one failure test so I can use it with my Arch Linux. Thanks you!

**Comment by sodabrew** [comment]
Thank you @m6w6! You've been on a tear recently! Really appreciate your work sprucing up this module. I'll be sure to update my test suite in php-memcached to use the latest msgpack-php, I hope you'll tag all this great work into a formal release version soon.

**Comment by m6w6** [comment]
Yes, I'm working on a new release.


And sorry, it looks like this PR could have been merged actually!

**Pull request closed without merging**
